#!/usr/bin/env python


from os import environ
from pathlib import Path
import pandas as pd
import subprocess as sp
from multiprocessing import Pool
import re

MUSIC = Path(environ["MEDIA"]) / "Music"
DB = MUSIC / ".songs.csv"
FORMAT = ".m4a"


def get_song(row):
    id = row["Video ID"]

    title = row["Song Title"].replace("/", "_").replace("'", "")
    title = re.sub(r"\(.*\)", "", title).strip()

    artist = row["Artist Name 1"].replace("/", "_").replace("'", "")
    artist = re.sub("The", "", artist).strip()

    filename = f"{artist} - {title}".strip()
    filepath = MUSIC / f"{filename}"

    if not filepath.with_suffix(FORMAT).is_file():
        print(f"Downloading {filename}")
        sp.call(
            [
                "yt-dlp",
                "-x",
                "--audio-quality",
                "2",
                "-o",
                filepath,
                f"https://www.youtube.com/watch?v={id}",
            ],
            stdout=sp.DEVNULL,  # Suppress standard output
            stderr=sp.DEVNULL,  # Suppress standard error
        )
    else:
        print(f"Downloading {artist} - {title} ... Already downloaded")


def get_songs():
    df = pd.read_csv(DB)
    return df.to_dict(orient="records")


def main():
    print("Starting downloads")
    songs = get_songs()
    print(f"There are {len(songs)} songs to download")
    with Pool() as p:
        p.imap_unordered(get_song, songs, chunksize=16)
        p.close()
        p.join()


if __name__ == "__main__":
    main()
